version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - app-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-cogopii1hbls7389tr4g-a.frankfurt-postgres.render.com:5432/coin_app_db
      - SPRING_DATASOURCE_USERNAME=coin_app_db_user
      - SPRING_DATASOURCE_PASSWORD=84bXznO8LdEC0lG0HhqhRk2MKn3XcyWq
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '7133:7133'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
